language: node_js
dist: trusty
node_js: 8.9
sudo: required

script:
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || [ "$TRAVIS_BRANCH" = "master" ]; then
      npm test;
    fi

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
