language: node_js
dist: trusty
node_js: 8.9
sudo: required

script:
  - if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || [ "$TRAVIS_BRANCH" = "master" ]; then
      travis_retry npm test;
    fi

notifications:
  email:
    on_success: never
